version: '3.1'
services:
  app:
    container_name: flashcard-app
    image: flashcard-app
    build: ./
    ports:
      - "4000:4000"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=112212
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flashcardApp